import json
import pandas

import re
import shlex
import os
import glob

path = 'C:/Users/Piece/Desktop/python/test3'

upgrades_keys=[
    ["m_mapAbilityProperties","*","m_strValue"],
    "_multibase",
]
hero_usefull_keys=[
    ["m_mapStartingStats"],
    ["m_mapStandardLevelUpUpgrades"],
    ["m_mapScalingStats"],
]
starting_stats_keys_backup=[
"EMaxMoveSpeed",
"ESprintSpeed",
"ECrouchSpeed",
"EMoveAcceleration",
"ELightMeleeDamage",
"EHeavyMeleeDamage",
"EMaxHealth",
"EWeaponPower",
"EReloadSpeed",
"EWeaponPowerScale",
"EProcBuildUpRateScale",
"EStamina",
"EBaseHealthRegen",
"EStaminaRegenPerSecond",
"EAbilityResourceMax",
"EAbilityResourceRegenPerSecond",
"ECritDamageReceivedScale",
"ETechDuration",
"ETechRange",
"EBulletArmorDamageReduction",
"ETechArmorDamageReduction",
"EMaxMoveSpeed",
"ESprintSpeed",
"ECrouchSpeed",
"EMoveAcceleration",
"ELightMeleeDamage",
"EHeavyMeleeDamage",
"EMaxHealth",
"EWeaponPower",
"EReloadSpeed",
"EWeaponPowerScale",
"EProcBuildUpRateScale",
"EStamina",
"EBaseHealthRegen",
"EStaminaRegenPerSecond",
"EAbilityResourceMax",
"EAbilityResourceRegenPerSecond",
"ECritDamageReceivedScale",
"ETechDuration",
"ETechRange",
"EBulletArmorDamageReduction",
"ETechArmorDamageReduction",
]
levelup_upgrades_keys_backup=[
"EMaxMoveSpeed",
"ESprintSpeed",
"ECrouchSpeed",
"EMoveAcceleration",
"ELightMeleeDamage",
"EHeavyMeleeDamage",
"EMaxHealth",
"EWeaponPower",
"EReloadSpeed",
"EWeaponPowerScale",
"EProcBuildUpRateScale",
"EStamina",
"EBaseHealthRegen",
"EStaminaRegenPerSecond",
"EAbilityResourceMax",
"EAbilityResourceRegenPerSecond",
"ECritDamageReceivedScale",
"ETechDuration",
"ETechRange",
"EBulletArmorDamageReduction",
"ETechArmorDamageReduction",
"MODIFIER_VALUE_BASE_BULLET_DAMAGE_FROM_LEVEL",
"MODIFIER_VALUE_BASE_MELEE_DAMAGE_FROM_LEVEL",
"MODIFIER_VALUE_BASE_HEALTH_FROM_LEVEL",
"MODIFIER_VALUE_TECH_DAMAGE_PERCENT",
"MODIFIER_VALUE_BULLET_ARMOR_DAMAGE_RESIST",
"MODIFIER_VALUE_BONUS_ATTACK_RANGE",
]
hero_collums_backup=[
"hero_base",
"hero_astro",
"hero_atlas",
"hero_bebop",
"hero_bomber",
"hero_cadence",
"hero_chrono",
"hero_dynamo",
"hero_forge",
"hero_genericperson",
"hero_ghost",
"hero_gigawatt",
"hero_gunslinger",
"hero_haze",
"hero_hornet",
"hero_inferno",
"hero_kali",
"hero_kelvin",
"hero_krill",
"hero_lash",
"hero_mirage",
"hero_nano",
"hero_orion",
"hero_rutger",
"hero_shiv",
"hero_slork",
"hero_synth",
"hero_targetdummy",
"hero_tengu",
"hero_thumper",
"hero_tokamak",
"hero_viscous",
"hero_warden",
"hero_wraith",
"hero_wrecker",
"hero_yakuza",
"hero_yamato",
]

collums_ability_properties=[
" AmmoPerSoul ",
" SpiritPowerPerSoul ",
" MaxStacks ",
" CaptureRadius ",
" TetherDuration ",
" TetherRadius ",
" TechRangeMultiplier ",
" TechRadiusMultiplier ",
" DebuffDuration ",
" StartRadius ",
" InvisAlertWhenFading ",
" InvisCancelOnDamage ",
" InvisFadeToDuration ",
" InvisMoveSpeedMod ",
" SpottedRadius ",
" RevealOnDamageDuration ",
" RevealOnSpottedDuration ",
" FullInvisDistance ",
" TempTechShieldHealth ",
" SpiritStolePerHit ",
" HeadshotBonusSteal ",
" ProcCooldown ",
" StealDuration ",
" BonusAbilityDurationPercent ",
" MinimumDamage ",
" ResistReduction ",
" BulletShieldDamagePercent ",
" AbilityLifestealPercentHero ",
" BulletResistReduction ",
" MagicResistReduction ",
" SpinUpTime ",
" SpinUpDecay ",
" InitialFireRateDecrease ",
" MaxFireRateIncrease ",
" BonusReloadTime ",
" DamageDuration ",
" DamageToStack ",
" WeaponPowerPerStack ",
" BonusClipSize ",
" LocalBulletArmorReduction ",
" BonusAbilityCharges ",
" SlowPercent ",
" SlowDuration ",
" LifestealHeal ",
" LifestealHealPercent ",
" NonHeroHealPct ",
" BulletArmorReduction ",
" FireRateSlow ",
" SingleTargetPlayerMultiplier ",
" ActivatedFireRate ",
" SlideScale ",
" CycleTimeFireRateDecrease ",
" BurstFireShotPercent ",
" NormalizedClipEmptySpeedIncrease ",
" BurstFireShotsFromClipPercent ",
" PerfectBurstWeaponPower ",
" BonusHeadshotDamage ",
" BaseBonusWeaponPower ",
" IntraBurstFireRateIncrease ",
" NonBurstFireConversionFactor ",
" MovementThresholdSq ",
" RegenWhileInvisible ",
" SlowResistancePercent ",
" DamagePerChain ",
" BonusPerChain ",
" ChainRadius ",
" ProcChance ",
" ChainCount ",
" ChainTickRate ",
" CooldownBetweenChargeReduction ",
" BonusChargedAbilityDamage ",
" BonusChargedCooldownReduction ",
" CooldownReductionFlat ",
" LightMeleeTimeWindow ",
" DamagePulseAmount ",
" PulseInterval ",
" PulseRadius ",
" DeathImmunityDuration ",
" DeathImmunityPulseRateMultiplier ",
" RestoreDelay ",
" HealLifePercentOutOfCombat ",
" HealthThreshold ",
" AmbushDuration ",
" AmbushBonusFireRate ",
" AmbushBonusTechPower ",
" CloseRangeBonusWeaponPower ",
" CloseRangeBonusDamageRange ",
" Stamina ",
" SpreadDuration ",
" EndRadius ",
" Damage ",
" GroundDashReductionPercent ",
" ModelScaleGrowth ",
" TechArmor ",
" HealPercentAmount ",
" RegenDuration ",
" ImbuedCooldownReduction ",
" NonImbuedCooldownReduction ",
" ProcBonusMagicDamage ",
" SpiritPower ",
" CritDamagePercent ",
" StatusResistancePercent ",
" SpiritSteal ",
" SpiritStealDuration ",
" HealAmpReceivePenaltyPercent ",
" HealAmpRegenPenaltyPercent ",
" MaxHealthPercentAsDPS ",
" MaxHealthPercentAsHealPerSecond ",
" AuraRadius ",
" BulletShieldOnCast ",
" TechShieldOnCast ",
" BuffDuration ",
" CooldownReduction ",
" AirJumps ",
" AirJumpVerticalSpeedPercent ",
" InteruptCooldown ",
" BonusFireRatePlayerUnit ",
" ActiveRadius ",
" ActiveBonusMoveSpeed ",
" MagicIncreasePerStack ",
" BonusSpiritForChargedAbilities ",
" CooldownReductionOnChargedAbilities ",
" LowHealthThreshold ",
" FervorMovespeed ",
" FervorFireRate ",
" FervorTechResist ",
" LingerDuration ",
" BonusFireRateNPC ",
" MoveWhileShootingSpeedPenaltyReductionPercent ",
" MoveWhileZoomedSpeedPenaltyReductionPercent ",
" BonusClipDuration ",
" LowHealthPercentThreshold ",
" LowHealthLifeStealPercent ",
" KillBonusMoveSpeedPerStack ",
" MaxKillBonusMoveSpeedStack ",
" BonusDamagePerHero ",
" GalvanicDebuffDuration ",
" GalvanicBuffDuration ",
" BuffDamageMult ",
" BuffMoveSpeedBonus ",
" MaxHealthLossPercent ",
" BonusClipPerKill ",
" MaxClipBonus ",
" WeaponPowerPerKill ",
" SkipFrames ",
" BonusBulletSpeedPercent ",
" HeadShotBonusDamage ",
" HeadShotCooldown ",
" HealPercentPerHeadshot ",
" MovementSpeedBonusDuration ",
" HealOnKill ",
" HealAmpCastPercent ",
" HealAmpRegenPercent ",
" DegenResistance ",
" TotalHealthRegen ",
" HeroTargetBonus ",
" HealInterval ",
" HealAmount ",
" HealRadius ",
" NonHeroAbilityLifestealTooltipOnly ",
" HighGroundBonusWeaponPower ",
" DamageThreshold ",
" DamageReduction ",
" LifeThreshold ",
" ImbuedBonusDuration ",
" ImbuedBonusDamage ",
" NonImbuedBonusDuration ",
" StaminaCooldownReduction ",
" BonusSpirit ",
" OutgoingAbilityDamagePenaltyPercent ",
" OutgoingBulletDamagePenaltyPercent ",
" ShootDurationForMax ",
" BaseAttackDamagePercentAtMaxDuration ",
" LifestrikeHeal ",
" LifestrikeHealPercent ",
" LongRangeBonusWeaponPower ",
" LongRangeBonusWeaponPowerMinRange ",
" SummonDuration ",
" ShieldDuration ",
" FlyingBulletShield ",
" FlyingTechShield ",
" FlyMoveSpeed ",
" BonusMovespeed ",
" BonusSpiritMaxTime ",
" BonusSpiritWindow ",
" BonusSpiritMin ",
" BonusSpiritWithMagicShield ",
" CooldownReductionWithShield ",
" ReProcLockoutTime ",
" MaxHealthDamage ",
" MovementSpeedSlow ",
" ImbuedTechPower ",
" HealFromHero ",
" HealFromNPC ",
" MeleeDistanceScale ",
" DPS ",
" DPSIncrease ",
" DPSMax ",
" TickRate ",
" MinTargetsRequired ",
" NonPlayerBonusWeaponPower ",
" NonPlayerBulletResist ",
" RespawnDelay ",
" RespawnBonusHealthDuration ",
" ImpactDamage ",
" EnemyLifeThreshold ",
" BaseAttackDamagePercentBonus ",
" ImmunityDuration ",
" BuildUpPerShot ",
" BuildUpDuration ",
" EMPDuration ",
" EMPProcChance ",
" BaseDamagePct ",
" NanoTechPerShot ",
" BaseDamagePerShot ",
" SpellAmplificationMultiplier ",
" FireRateBonus ",
" FireRateDuration ",
" MaxHealth ",
" RespawnHealthPercent ",
" AttackDamageWhenShielded ",
" FireRateWhenShielded ",
" MaxArmorStacks ",
" BulletResistPerStack ",
" BulletResistDuration ",
" SelfModifier ",
" HealPerStack ",
" BulletDamageReflectedPct ",
" SpiritDamageReflectedPct ",
" RicochetDamagePercent ",
" RicochetRadius ",
" RicochetTargetsTooltipOnly ",
" AirControlPercent ",
" SlamDownRadius ",
" VerticalDifferenceTolerance ",
" TossSpeed ",
" DropDownSpeed ",
" ImpactHeight ",
" MinAimAngle ",
" DotHealthPercent ",
" SaviorBulletShieldHealth ",
" SaviorMagicShieldHealth ",
" BonusSpiritDuration ",
" DampingFactor ",
" LiftHeight ",
" MoveSpeedMax ",
" BonusAttackRangePercent ",
" BonusZoomPercent ",
" StealPerHit ",
" StackLostPerDeath ",
" HealthSteal ",
" ParticleRadius ",
" ModelScale ",
" TrackingSpeed ",
" TurretAttackDelay ",
" TurretAttackRange ",
" TurretDeployTime ",
" TurretLifetime ",
" AttackConeAngle ",
" StationaryWeaponPower ",
" StationaryRecoilReduction ",
" CasterHealthPercent ",
" BulletSpeedOverride ",
" StasisRadius ",
" ExplodeDamage ",
" StunDuration ",
" MaxFallSpeed ",
" SlamdownSpeed ",
" AirMoveIncreasePercent ",
" ActiveBonusFireRate ",
" ActiveBonusLifesteal ",
" ActiveReloadPercent ",
" StunDelay ",
" VisualContractRadius ",
" TechDamagePercent ",
" DelayDuration ",
" TechCleaveDamagePercent ",
" TechCleaveRadius ",
" DamagePulseRadius ",
" ShreddersTechAmp ",
" NonImbuedTechRangeMultiplier ",
" NonImbuedTechRadiusMultiplier ",
" ImbuedTechRangeMultiplier ",
" ImbuedTechRadiusMultiplier ",
" NonHeroReductionPercent ",
" HeightOffGround ",
" BonusBaseWeaponDamageTaken ",
" DotDuration ",
" DotMultiplerTroopers ",
" InvisDuration ",
" VexBarrierBulletMaxHealth ",
" VexBarrierTechMaxHealth ",
" VexBarrierShieldDuration ",
" CasterBuffDuration ",
" WeaponPowerPerDeath ",
" KillWindow ",
" MaxWeaponPower ",
" BaseBonusCounter ",
" HealthDamagePercent ",
" BonusReloadSpeed ",
" BonusWeaponPower ",
" OverdriveClipDuration ",
" WeaponPowerWhileActivated ",
" HealthDrainedPerSecond ",
" Interval ",
" AbilityCooldown ",
" AbilityDuration ",
" AbilityCastRange ",
" AbilityUnitTargetLimit ",
" AbilityCastDelay ",
" AbilityChannelTime ",
" AbilityPostCastDuration ",
" AbilityCharges ",
" AbilityCooldownBetweenCharge ",
" ChannelMoveSpeed ",
" AbilityResourceCost ",
" TechPower ",
" WeaponPower ",
" BonusMoveSpeed ",
" BulletResist ",
" TechResist ",
" MaxBulletResist ",
" StackLossFrequency ",
" ArmorLossPerHit ",
" BulletArmor ",
" BonusSprintSpeed ",
" SpiritDamage ",
" TechArmorDamageReduction ",
" TechShieldMaxHealth ",
" BonusHealthRegen ",
" BonusMeleeDamagePercent ",
" TempBulletShieldHealth ",
" Radius ",
" BulletShieldMaxHealth ",
" BaseAttackDamagePercent ",
" ReloadSpeedMultipler ",
" BulletLifestealPercent ",
" BonusFireRate ",
" ActivateTime ",
" JumpVelocityHidden ",
" AssaultLifestealPercent ",
" AssaultDuration ",
" AssaultFireRate ",
" ExplodeRadius ",
" BonusClipSizePercent ",
" BonusHealth ",
" AmmoPerSoul ",
" SpiritPowerPerSoul ",
" MaxStacks ",
" CaptureRadius ",
" TetherDuration ",
" TetherRadius ",
" TechRangeMultiplier ",
" TechRadiusMultiplier ",
" DebuffDuration ",
" StartRadius ",
" InvisAlertWhenFading ",
" InvisCancelOnDamage ",
" InvisFadeToDuration ",
" InvisMoveSpeedMod ",
" SpottedRadius ",
" RevealOnDamageDuration ",
" RevealOnSpottedDuration ",
" FullInvisDistance ",
" TempTechShieldHealth ",
" SpiritStolePerHit ",
" HeadshotBonusSteal ",
" ProcCooldown ",
" StealDuration ",
" BonusAbilityDurationPercent ",
" MinimumDamage ",
" ResistReduction ",
" BulletShieldDamagePercent ",
" AbilityLifestealPercentHero ",
" BulletResistReduction ",
" MagicResistReduction ",
" SpinUpTime ",
" SpinUpDecay ",
" InitialFireRateDecrease ",
" MaxFireRateIncrease ",
" BonusReloadTime ",
" DamageDuration ",
" DamageToStack ",
" WeaponPowerPerStack ",
" BonusClipSize ",
" LocalBulletArmorReduction ",
" BonusAbilityCharges ",
" SlowPercent ",
" SlowDuration ",
" LifestealHeal ",
" LifestealHealPercent ",
" NonHeroHealPct ",
" BulletArmorReduction ",
" FireRateSlow ",
" SingleTargetPlayerMultiplier ",
" ActivatedFireRate ",
" SlideScale ",
" CycleTimeFireRateDecrease ",
" BurstFireShotPercent ",
" NormalizedClipEmptySpeedIncrease ",
" BurstFireShotsFromClipPercent ",
" PerfectBurstWeaponPower ",
" BonusHeadshotDamage ",
" BaseBonusWeaponPower ",
" IntraBurstFireRateIncrease ",
" NonBurstFireConversionFactor ",
" MovementThresholdSq ",
" RegenWhileInvisible ",
" SlowResistancePercent ",
" DamagePerChain ",
" BonusPerChain ",
" ChainRadius ",
" ProcChance ",
" ChainCount ",
" ChainTickRate ",
" CooldownBetweenChargeReduction ",
" BonusChargedAbilityDamage ",
" BonusChargedCooldownReduction ",
" CooldownReductionFlat ",
" LightMeleeTimeWindow ",
" DamagePulseAmount ",
" PulseInterval ",
" PulseRadius ",
" DeathImmunityDuration ",
" DeathImmunityPulseRateMultiplier ",
" RestoreDelay ",
" HealLifePercentOutOfCombat ",
" HealthThreshold ",
" AmbushDuration ",
" AmbushBonusFireRate ",
" AmbushBonusTechPower ",
" CloseRangeBonusWeaponPower ",
" CloseRangeBonusDamageRange ",
" Stamina ",
" SpreadDuration ",
" EndRadius ",
" Damage ",
" GroundDashReductionPercent ",
" ModelScaleGrowth ",
" TechArmor ",
" HealPercentAmount ",
" RegenDuration ",
" ImbuedCooldownReduction ",
" NonImbuedCooldownReduction ",
" ProcBonusMagicDamage ",
" SpiritPower ",
" CritDamagePercent ",
" StatusResistancePercent ",
" SpiritSteal ",
" SpiritStealDuration ",
" HealAmpReceivePenaltyPercent ",
" HealAmpRegenPenaltyPercent ",
" MaxHealthPercentAsDPS ",
" MaxHealthPercentAsHealPerSecond ",
" AuraRadius ",
" BulletShieldOnCast ",
" TechShieldOnCast ",
" BuffDuration ",
" CooldownReduction ",
" AirJumps ",
" AirJumpVerticalSpeedPercent ",
" InteruptCooldown ",
" BonusFireRatePlayerUnit ",
" ActiveRadius ",
" ActiveBonusMoveSpeed ",
" MagicIncreasePerStack ",
" BonusSpiritForChargedAbilities ",
" CooldownReductionOnChargedAbilities ",
" LowHealthThreshold ",
" FervorMovespeed ",
" FervorFireRate ",
" FervorTechResist ",
" LingerDuration ",
" BonusFireRateNPC ",
" MoveWhileShootingSpeedPenaltyReductionPercent ",
" MoveWhileZoomedSpeedPenaltyReductionPercent ",
" BonusClipDuration ",
" LowHealthPercentThreshold ",
" LowHealthLifeStealPercent ",
" KillBonusMoveSpeedPerStack ",
" MaxKillBonusMoveSpeedStack ",
" BonusDamagePerHero ",
" GalvanicDebuffDuration ",
" GalvanicBuffDuration ",
" BuffDamageMult ",
" BuffMoveSpeedBonus ",
" MaxHealthLossPercent ",
" BonusClipPerKill ",
" MaxClipBonus ",
" WeaponPowerPerKill ",
" SkipFrames ",
" BonusBulletSpeedPercent ",
" HeadShotBonusDamage ",
" HeadShotCooldown ",
" HealPercentPerHeadshot ",
" MovementSpeedBonusDuration ",
" HealOnKill ",
" HealAmpCastPercent ",
" HealAmpRegenPercent ",
" DegenResistance ",
" TotalHealthRegen ",
" HeroTargetBonus ",
" HealInterval ",
" HealAmount ",
" HealRadius ",
" NonHeroAbilityLifestealTooltipOnly ",
" HighGroundBonusWeaponPower ",
" DamageThreshold ",
" DamageReduction ",
" LifeThreshold ",
" ImbuedBonusDuration ",
" ImbuedBonusDamage ",
" NonImbuedBonusDuration ",
" StaminaCooldownReduction ",
" BonusSpirit ",
" OutgoingAbilityDamagePenaltyPercent ",
" OutgoingBulletDamagePenaltyPercent ",
" ShootDurationForMax ",
" BaseAttackDamagePercentAtMaxDuration ",
" LifestrikeHeal ",
" LifestrikeHealPercent ",
" LongRangeBonusWeaponPower ",
" LongRangeBonusWeaponPowerMinRange ",
" SummonDuration ",
" ShieldDuration ",
" FlyingBulletShield ",
" FlyingTechShield ",
" FlyMoveSpeed ",
" BonusMovespeed ",
" BonusSpiritMaxTime ",
" BonusSpiritWindow ",
" BonusSpiritMin ",
" BonusSpiritWithMagicShield ",
" CooldownReductionWithShield ",
" ReProcLockoutTime ",
" MaxHealthDamage ",
" MovementSpeedSlow ",
" ImbuedTechPower ",
" HealFromHero ",
" HealFromNPC ",
" MeleeDistanceScale ",
" DPS ",
" DPSIncrease ",
" DPSMax ",
" TickRate ",
" MinTargetsRequired ",
" NonPlayerBonusWeaponPower ",
" NonPlayerBulletResist ",
" RespawnDelay ",
" RespawnBonusHealthDuration ",
" ImpactDamage ",
" EnemyLifeThreshold ",
" BaseAttackDamagePercentBonus ",
" ImmunityDuration ",
" BuildUpPerShot ",
" BuildUpDuration ",
" EMPDuration ",
" EMPProcChance ",
" BaseDamagePct ",
" NanoTechPerShot ",
" BaseDamagePerShot ",
" SpellAmplificationMultiplier ",
" FireRateBonus ",
" FireRateDuration ",
" MaxHealth ",
" RespawnHealthPercent ",
" AttackDamageWhenShielded ",
" FireRateWhenShielded ",
" MaxArmorStacks ",
" BulletResistPerStack ",
" BulletResistDuration ",
" SelfModifier ",
" HealPerStack ",
" BulletDamageReflectedPct ",
" SpiritDamageReflectedPct ",
" RicochetDamagePercent ",
" RicochetRadius ",
" RicochetTargetsTooltipOnly ",
" AirControlPercent ",
" SlamDownRadius ",
" VerticalDifferenceTolerance ",
" TossSpeed ",
" DropDownSpeed ",
" ImpactHeight ",
" MinAimAngle ",
" DotHealthPercent ",
" SaviorBulletShieldHealth ",
" SaviorMagicShieldHealth ",
" BonusSpiritDuration ",
" DampingFactor ",
" LiftHeight ",
" MoveSpeedMax ",
" BonusAttackRangePercent ",
" BonusZoomPercent ",
" StealPerHit ",
" StackLostPerDeath ",
" HealthSteal ",
" ParticleRadius ",
" ModelScale ",
" TrackingSpeed ",
" TurretAttackDelay ",
" TurretAttackRange ",
" TurretDeployTime ",
" TurretLifetime ",
" AttackConeAngle ",
" StationaryWeaponPower ",
" StationaryRecoilReduction ",
" CasterHealthPercent ",
" BulletSpeedOverride ",
" StasisRadius ",
" ExplodeDamage ",
" StunDuration ",
" MaxFallSpeed ",
" SlamdownSpeed ",
" AirMoveIncreasePercent ",
" ActiveBonusFireRate ",
" ActiveBonusLifesteal ",
" ActiveReloadPercent ",
" StunDelay ",
" VisualContractRadius ",
" TechDamagePercent ",
" DelayDuration ",
" TechCleaveDamagePercent ",
" TechCleaveRadius ",
" DamagePulseRadius ",
" ShreddersTechAmp ",
" NonImbuedTechRangeMultiplier ",
" NonImbuedTechRadiusMultiplier ",
" ImbuedTechRangeMultiplier ",
" ImbuedTechRadiusMultiplier ",
" NonHeroReductionPercent ",
" HeightOffGround ",
" BonusBaseWeaponDamageTaken ",
" DotDuration ",
" DotMultiplerTroopers ",
" InvisDuration ",
" VexBarrierBulletMaxHealth ",
" VexBarrierTechMaxHealth ",
" VexBarrierShieldDuration ",
" CasterBuffDuration ",
" WeaponPowerPerDeath ",
" KillWindow ",
" MaxWeaponPower ",
" BaseBonusCounter ",
" HealthDamagePercent ",
" BonusReloadSpeed ",
" BonusWeaponPower ",
" OverdriveClipDuration ",
" WeaponPowerWhileActivated ",
" HealthDrainedPerSecond ",
" Interval ",
" AbilityCooldown ",
" AbilityDuration ",
" AbilityCastRange ",
" AbilityUnitTargetLimit ",
" AbilityCastDelay ",
" AbilityChannelTime ",
" AbilityPostCastDuration ",
" AbilityCharges ",
" AbilityCooldownBetweenCharge ",
" ChannelMoveSpeed ",
" AbilityResourceCost ",
" TechPower ",
" WeaponPower ",
" BonusMoveSpeed ",
" BulletResist ",
" TechResist ",
" MaxBulletResist ",
" StackLossFrequency ",
" ArmorLossPerHit ",
" BulletArmor ",
" BonusSprintSpeed ",
" SpiritDamage ",
" TechArmorDamageReduction ",
" TechShieldMaxHealth ",
" BonusHealthRegen ",
" BonusMeleeDamagePercent ",
" TempBulletShieldHealth ",
" Radius ",
" BulletShieldMaxHealth ",
" BaseAttackDamagePercent ",
" ReloadSpeedMultipler ",
" BulletLifestealPercent ",
" BonusFireRate ",
" ActivateTime ",
" JumpVelocityHidden ",
" AssaultLifestealPercent ",
" AssaultDuration ",
" AssaultFireRate ",
" ExplodeRadius ",
" BonusClipSizePercent ",
" BonusHealth ",
" AmmoPerSoul ",
" SpiritPowerPerSoul ",
" MaxStacks ",
" CaptureRadius ",
" TetherDuration ",
" TetherRadius ",
" TechRangeMultiplier ",
" TechRadiusMultiplier ",
" DebuffDuration ",
" StartRadius ",
" InvisAlertWhenFading ",
" InvisCancelOnDamage ",
" InvisFadeToDuration ",
" InvisMoveSpeedMod ",
" SpottedRadius ",
" RevealOnDamageDuration ",
" RevealOnSpottedDuration ",
" FullInvisDistance ",
" TempTechShieldHealth ",
" SpiritStolePerHit ",
" HeadshotBonusSteal ",
" ProcCooldown ",
" StealDuration ",
" BonusAbilityDurationPercent ",
" MinimumDamage ",
" ResistReduction ",
" BulletShieldDamagePercent ",
" AbilityLifestealPercentHero ",
" BulletResistReduction ",
" MagicResistReduction ",
" SpinUpTime ",
" SpinUpDecay ",
" InitialFireRateDecrease ",
" MaxFireRateIncrease ",
" BonusReloadTime ",
" DamageDuration ",
" DamageToStack ",
" WeaponPowerPerStack ",
" BonusClipSize ",
" LocalBulletArmorReduction ",
" BonusAbilityCharges ",
" SlowPercent ",
" SlowDuration ",
" LifestealHeal ",
" LifestealHealPercent ",
" NonHeroHealPct ",
" BulletArmorReduction ",
" FireRateSlow ",
" SingleTargetPlayerMultiplier ",
" ActivatedFireRate ",
" SlideScale ",
" CycleTimeFireRateDecrease ",
" BurstFireShotPercent ",
" NormalizedClipEmptySpeedIncrease ",
" BurstFireShotsFromClipPercent ",
" PerfectBurstWeaponPower ",
" BonusHeadshotDamage ",
" BaseBonusWeaponPower ",
" IntraBurstFireRateIncrease ",
" NonBurstFireConversionFactor ",
" MovementThresholdSq ",
" RegenWhileInvisible ",
" SlowResistancePercent ",
" DamagePerChain ",
" BonusPerChain ",
" ChainRadius ",
" ProcChance ",
" ChainCount ",
" ChainTickRate ",
" CooldownBetweenChargeReduction ",
" BonusChargedAbilityDamage ",
" BonusChargedCooldownReduction ",
" CooldownReductionFlat ",
" LightMeleeTimeWindow ",
" DamagePulseAmount ",
" PulseInterval ",
" PulseRadius ",
" DeathImmunityDuration ",
" DeathImmunityPulseRateMultiplier ",
" RestoreDelay ",
" HealLifePercentOutOfCombat ",
" HealthThreshold ",
" AmbushDuration ",
" AmbushBonusFireRate ",
" AmbushBonusTechPower ",
" CloseRangeBonusWeaponPower ",
" CloseRangeBonusDamageRange ",
" Stamina ",
" SpreadDuration ",
" EndRadius ",
" Damage ",
" GroundDashReductionPercent ",
" ModelScaleGrowth ",
" TechArmor ",
" HealPercentAmount ",
" RegenDuration ",
" ImbuedCooldownReduction ",
" NonImbuedCooldownReduction ",
" ProcBonusMagicDamage ",
" SpiritPower ",
" CritDamagePercent ",
" StatusResistancePercent ",
" SpiritSteal ",
" SpiritStealDuration ",
" HealAmpReceivePenaltyPercent ",
" HealAmpRegenPenaltyPercent ",
" MaxHealthPercentAsDPS ",
" MaxHealthPercentAsHealPerSecond ",
" AuraRadius ",
" BulletShieldOnCast ",
" TechShieldOnCast ",
" BuffDuration ",
" CooldownReduction ",
" AirJumps ",
" AirJumpVerticalSpeedPercent ",
" InteruptCooldown ",
" BonusFireRatePlayerUnit ",
" ActiveRadius ",
" ActiveBonusMoveSpeed ",
" MagicIncreasePerStack ",
" BonusSpiritForChargedAbilities ",
" CooldownReductionOnChargedAbilities ",
" LowHealthThreshold ",
" FervorMovespeed ",
" FervorFireRate ",
" FervorTechResist ",
" LingerDuration ",
" BonusFireRateNPC ",
" MoveWhileShootingSpeedPenaltyReductionPercent ",
" MoveWhileZoomedSpeedPenaltyReductionPercent ",
" BonusClipDuration ",
" LowHealthPercentThreshold ",
" LowHealthLifeStealPercent ",
" KillBonusMoveSpeedPerStack ",
" MaxKillBonusMoveSpeedStack ",
" BonusDamagePerHero ",
" GalvanicDebuffDuration ",
" GalvanicBuffDuration ",
" BuffDamageMult ",
" BuffMoveSpeedBonus ",
" MaxHealthLossPercent ",
" BonusClipPerKill ",
" MaxClipBonus ",
" WeaponPowerPerKill ",
" SkipFrames ",
" BonusBulletSpeedPercent ",
" HeadShotBonusDamage ",
" HeadShotCooldown ",
" HealPercentPerHeadshot ",
" MovementSpeedBonusDuration ",
" HealOnKill ",
" HealAmpCastPercent ",
" HealAmpRegenPercent ",
" DegenResistance ",
" TotalHealthRegen ",
" HeroTargetBonus ",
" HealInterval ",
" HealAmount ",
" HealRadius ",
" NonHeroAbilityLifestealTooltipOnly ",
" HighGroundBonusWeaponPower ",
" DamageThreshold ",
" DamageReduction ",
" LifeThreshold ",
" ImbuedBonusDuration ",
" ImbuedBonusDamage ",
" NonImbuedBonusDuration ",
" StaminaCooldownReduction ",
" BonusSpirit ",
" OutgoingAbilityDamagePenaltyPercent ",
" OutgoingBulletDamagePenaltyPercent ",
" ShootDurationForMax ",
" BaseAttackDamagePercentAtMaxDuration ",
" LifestrikeHeal ",
" LifestrikeHealPercent ",
" LongRangeBonusWeaponPower ",
" LongRangeBonusWeaponPowerMinRange ",
" SummonDuration ",
" ShieldDuration ",
" FlyingBulletShield ",
" FlyingTechShield ",
" FlyMoveSpeed ",
" BonusMovespeed ",
" BonusSpiritMaxTime ",
" BonusSpiritWindow ",
" BonusSpiritMin ",
" BonusSpiritWithMagicShield ",
" CooldownReductionWithShield ",
" ReProcLockoutTime ",
" MaxHealthDamage ",
" MovementSpeedSlow ",
" ImbuedTechPower ",
" HealFromHero ",
" HealFromNPC ",
" MeleeDistanceScale ",
" DPS ",
" DPSIncrease ",
" DPSMax ",
" TickRate ",
" MinTargetsRequired ",
" NonPlayerBonusWeaponPower ",
" NonPlayerBulletResist ",
" RespawnDelay ",
" RespawnBonusHealthDuration ",
" ImpactDamage ",
" EnemyLifeThreshold ",
" BaseAttackDamagePercentBonus ",
" ImmunityDuration ",
" BuildUpPerShot ",
" BuildUpDuration ",
" EMPDuration ",
" EMPProcChance ",
" BaseDamagePct ",
" NanoTechPerShot ",
" BaseDamagePerShot ",
" SpellAmplificationMultiplier ",
" FireRateBonus ",
" FireRateDuration ",
" MaxHealth ",
" RespawnHealthPercent ",
" AttackDamageWhenShielded ",
" FireRateWhenShielded ",
" MaxArmorStacks ",
" BulletResistPerStack ",
" BulletResistDuration ",
" SelfModifier ",
" HealPerStack ",
" BulletDamageReflectedPct ",
" SpiritDamageReflectedPct ",
" RicochetDamagePercent ",
" RicochetRadius ",
" RicochetTargetsTooltipOnly ",
" AirControlPercent ",
" SlamDownRadius ",
" VerticalDifferenceTolerance ",
" TossSpeed ",
" DropDownSpeed ",
" ImpactHeight ",
" MinAimAngle ",
" DotHealthPercent ",
" SaviorBulletShieldHealth ",
" SaviorMagicShieldHealth ",
" BonusSpiritDuration ",
" DampingFactor ",
" LiftHeight ",
" MoveSpeedMax ",
" BonusAttackRangePercent ",
" BonusZoomPercent ",
" StealPerHit ",
" StackLostPerDeath ",
" HealthSteal ",
" ParticleRadius ",
" ModelScale ",
" TrackingSpeed ",
" TurretAttackDelay ",
" TurretAttackRange ",
" TurretDeployTime ",
" TurretLifetime ",
" AttackConeAngle ",
" StationaryWeaponPower ",
" StationaryRecoilReduction ",
" CasterHealthPercent ",
" BulletSpeedOverride ",
" StasisRadius ",
" ExplodeDamage ",
" StunDuration ",
" MaxFallSpeed ",
" SlamdownSpeed ",
" AirMoveIncreasePercent ",
" ActiveBonusFireRate ",
" ActiveBonusLifesteal ",
" ActiveReloadPercent ",
" StunDelay ",
" VisualContractRadius ",
" TechDamagePercent ",
" DelayDuration ",
" TechCleaveDamagePercent ",
" TechCleaveRadius ",
" DamagePulseRadius ",
" ShreddersTechAmp ",
" NonImbuedTechRangeMultiplier ",
" NonImbuedTechRadiusMultiplier ",
" ImbuedTechRangeMultiplier ",
" ImbuedTechRadiusMultiplier ",
" NonHeroReductionPercent ",
" HeightOffGround ",
" BonusBaseWeaponDamageTaken ",
" DotDuration ",
" DotMultiplerTroopers ",
" InvisDuration ",
" VexBarrierBulletMaxHealth ",
" VexBarrierTechMaxHealth ",
" VexBarrierShieldDuration ",
" CasterBuffDuration ",
" WeaponPowerPerDeath ",
" KillWindow ",
" MaxWeaponPower ",
" BaseBonusCounter ",
" HealthDamagePercent ",
" BonusReloadSpeed ",
" BonusWeaponPower ",
" OverdriveClipDuration ",
" WeaponPowerWhileActivated ",
" HealthDrainedPerSecond ",
" Interval ",
" CollisionDamage ",
" ZiplineJumpBonusMoveSpeed ",
" ZiplineJumpBonusTimeScale ",
" ZiplineJumpBonusDurationMax ",
]

lvlup_upgrades_keys=[]
lvlup_upgrades_data=[]
starting_stats_keys=[]
starting_stats_data=[]
hero_keys=[]


hero_collums=[]

for filename in glob.glob(os.path.join(path, '*.json')):
   with open(os.path.join(os.getcwd(), filename), 'r') as f:
        
        try:
            data =json.load(f) #получем стандартный python словар
            #print("Норм в ",f.name)
            for key in data.keys(): #Вход в основной словарь
                
                #print(data.get(key).get("m_mapAbilityProperties").get("AbilityCooldown").get("m_strValue"))
                if str(key).index("hero_")==0:
                    #df= pandas.DataFrame()
                    hero_keys.append(key)
                    starting_stats_data.append([])
                    lvlup_upgrades_data.append([])
                    starting_stats_data[hero_keys.index(key)] = [None]*len(starting_stats_keys)
                    lvlup_upgrades_data[hero_keys.index(key)] = [None]*len(lvlup_upgrades_keys)
                    
                    for value in data[key]["m_mapStartingStats"].keys():
                        #print(hero_keys.index(key))
                        value = str(value).strip()
                        if not (value in starting_stats_keys):                         
                            starting_stats_keys.append(value)
                            #print(data[key]["m_mapStartingStats"][value])
                            starting_stats_data[hero_keys.index(key)].append(data[key]["m_mapStartingStats"][value])
                        else:
                            #print(hero_keys.index(key))
                            #print(starting_stats_keys.index(value))
                            #print(value)
                            starting_stats_data[hero_keys.index(key)][starting_stats_keys.index(value)]=data[key]["m_mapStartingStats"][value]

                    for value in data[key]["m_mapStandardLevelUpUpgrades"].keys():
                        #print(hero_keys.index(key))
                        value = str(value).strip()
                        if not (value in lvlup_upgrades_keys):                         
                            lvlup_upgrades_keys.append(value)
                            #print(data[key]["m_mapStartingStats"][value])
                            lvlup_upgrades_data[hero_keys.index(key)].append(data[key]["m_mapStandardLevelUpUpgrades"][value])
                        else:
                            #print(hero_keys.index(key))
                            #print(starting_stats_keys.index(value))
                            #print(value)
                            lvlup_upgrades_data[hero_keys.index(key)][lvlup_upgrades_keys.index(value)]=data[key]["m_mapStandardLevelUpUpgrades"][value]
                            
                    #m_mapScalingStats
                    for value in data[key]["m_mapScalingStats"].keys():
                        #print(hero_keys.index(key))
                        value = str(value).strip()
                        if not (value in lvlup_upgrades_keys):                         
                            lvlup_upgrades_keys.append(value)
                            #print(data[key]["m_mapStartingStats"][value])
                            lvlup_upgrades_data[hero_keys.index(key)].append(data[key]["m_mapScalingStats"][value])
                        else:
                            #print(hero_keys.index(key))
                            #print(starting_stats_keys.index(value))
                            #print(value)
                            lvlup_upgrades_data[hero_keys.index(key)][lvlup_upgrades_keys.index(value)]=data[key]["m_mapScalingStats"][value]

#                    for value in data[key]["m_mapStandardLevelUpUpgrades"].keys():
#                        if not (str(value).strip() in lvlup_upgrades_keys):
#                            lvlup_upgrades_keys.append(str(value).strip())    
#                            print(value)               
#                        lvlup_upgrades_data[hero_keys.index(key)][lvlup_upgrades_keys.index(value)]=data[key]["m_mapStandardLevelUpUpgrades"][value]



                        #print(str(properties))
                        #print(str(key)," ",str(properties)," ",data[key]["m_mapAbilityProperties"][properties]["m_strValue"])
            

        except:
            print("fuck!")
            #print("Ошибка в ",print(f.name))

#levelup_upgrades_data =[["x"]*lvlup_upgrades_keys_count.count]*hero_count
#print(starting_stats_keys)
#for row in starting_stats_data:
#    print(row,sep="/n")
df = pandas.DataFrame(data=starting_stats_data,index=hero_keys,columns=starting_stats_keys)

excel_name = "C:/Users/Piece/Desktop/python/heroes_starting_stats.xlsx"
df.to_excel(excel_name)

excel_name = "C:/Users/Piece/Desktop/python/lvlup_upgrades_stats.xlsx"
df = pandas.DataFrame(data=lvlup_upgrades_data,index=hero_keys,columns=lvlup_upgrades_keys)
df.to_excel(excel_name)



#print(starting_stats_data)
